sudo: required
services:
  - docker
branches:
  only:
    - build
before_install:
  - sudo apt-get install jq
env:
  - ADDON="octoprint"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON
