sudo: required
services:
  - docker
branches:
  only:
    - build
before_install:
  - sudo apt-get install jq
  - sudo chmod +x ./build.sh
env:
  - ADDON=octoprint_dev ARCH=amd64
  - ADDON=octoprint_slim ARCH=amd64
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON
