sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
  - chmod +x build.sh
env:
  - ADDON="octoprint"
script:
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON
